# Generated by Django 4.2.3 on 2023-08-01 14:24

import django.core.validators
from django.db import migrations, models
import movie_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), movie_api.models.max_value_current_year], verbose_name='year'),
        ),
    ]
