# Generated by Django 4.2.3 on 2023-08-01 15:14

import django.core.validators
from django.db import migrations, models
import movie_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0003_alter_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(default='drama', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='descricao',
            field=models.TextField(default='good movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movies/images/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='titulo',
            field=models.CharField(default='the godfather', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1878), movie_api.models.max_value_current_year], verbose_name='year'),
        ),
    ]
