# Generated by Django 4.2.3 on 2023-08-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0004_remove_movie_description_remove_movie_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='titulo',
            new_name='title',
        ),
    ]
